### ISSUE TITLE
Battle.net issues (slow speeds, disconnections)

### ISSUE THREAD

**Issue by Dids** [steamcache/generic#10]
I've got a steamcache-dns, steamcache and steamcache-generic docker setup going, and it's working really well for everything except Battle.net.

I have a 100/20 connection, but with caching enabled, I only get 2-3mbps from Blizzard's servers, and I'm not sure why. I also get intermittent disconnections while downloading from Battle.net.

Just wondering if anyone else is also seeing this?

**Comment by Dids** [comment]
Hmm, I guess the disconnections could be due to this?
```
[error] 17#17: *72189 etag mismatch in slice response, client: 192.168.1.123, server: , request: "GET /tpr/d3/data/38/9a/389a13f170d40f370c0007d93599bd16 HTTP/1.1", subrequest: "/tpr/d3/data/38/9a/389a13f170d40f370c0007d93599bd16", host: "blzddist1-a.akamaihd.net"
```

**Comment by Dids** [comment]
Having trouble finish Overwatch install, as the last few dozen megabytes try to download, then it keeps throwing this:

![Battle.Net Caching Issues](http://i.imgur.com/lRGJc12.png)

**EDIT**: At the same time, there's a ton of new slice errors coming in.
**EDIT2**: Looks like it's an update for Overwatch instead of the initial install that keeps failing, if that helps.

**Comment by Dids** [comment]
Hmm, I tried kixelated's work from here:
https://github.com/kixelated/steamcache

So far I'm still seeing the slice errors, but not a single error client-side, and the download eventually finished.

I did however change global docker dns from Google to more local/preferred DNS, so not sure if that could've affected it?

**Comment by ekhoury2000** [comment]
hi @Dids 
seems no one replies here :)
i used the generic image too, download is working from proxy, but from internet too. (server and client download from internet and not only server). i guess there are w few CDN missing.

any ideas?

also, did u get all 3 dicker images on same server?

**Comment by Dids** [comment]
Hey @ekhoury2000! I'm using all three of kixelated's images (steamcache, steamcache-dns and steamcache-sni), and yes, running them on the same machine. They seem to be more maintained and more feature-complete.

My issues could stem from running them in a linux VM on top of Hyper-V (on physical ReFS partitions), but I kinda doubt it, because the networking itself works like a charm (fast too).

While cached downloads still seem to be slow (3mbps, compared to 10mbps on my 100/20 connection), the biggest issue I have is super slow or timing out of random DNS queries, but I believe I fixed that by not using Google's DNS for any of the containers.

**Comment by mintopia** [comment]
I haven't got as much time to work on the image as I'd like. There's a lot of good changes in @kixelated's fork and it would be good to get them back in to this branch.

I'm currently using this cache for Blizzard caching at EGX Rezzed for 15 PCs and not having any issues client-side. I'll grep the logs when I get some time to check out if I'm also getting the slice errors.

It's certainly possible there's CDN addresses missing. I'll try and look into it this week and find any missing ones.

I have a small LAN party next weekend so I'll be looking at getting the image updated with the latest changes and deployed to my live setup this week for testing at the event.

**Comment by ekhoury2000** [comment]
Hey @Dids @mintopia ,

By running all 3 images on the same machine, kixelated's images (steamcache, steamcache-dns and steamcache-sni), are u being able of caching steam, riot and blizzard games? because i had tested Kixelated's steamcache image and i did not perform as expected.

Do you recommend giving it a second chance?

I am using 3 images now, steamcache, steamcache-dns, and steamcache-generic on another server.

seems good so far, but i prefer to have one server instead of 2 so please let me know ,
Thanks

**Comment by Dids** [comment]
@ekhoury2000 I can confirm that caching for Steam, Origin, Blizzard and Windows Update works for me, as I'm using those four on a daily basis.

Be sure to bind all the ports necessary for all three containers. I also used `--network host` for all of these, mainly for the extra performance it should give.

**Comment by kixelated** [comment]
@ekhoury2000 You can't run steamcache and generic on the same host because they listen on the same port. You just want generic and steamcache-dns for the basic functionality. Steamcache only works for Steam, while generic works for Steam and other platforms as well.

My steamcache fork is actually just a better version of generic (supports all platforms), but I wanted to call my project steamcache anyway. It confuses the picture a little bit.

My suggestion would be to run kixelated/steamcache and kixelated/steamcache-dns. Optionally, you can also run kixelated/steamcache-sni to fix some issues with Origin. All of these images listen on different ports and can be run on the same host.

Also concerning the original issue, my fork should behave more or less the same way as generic for battle.net. I don't really have any insight into the issue or why my fork would work better in this case.

**Comment by Dids** [comment]
Since switching to the forks fixed the actual issue for me, and by the looks of it there aren't others who are seeing the same, I think it's safe to close this one.

Do keep in mind that it might've been a configuration error on my part, a temporary issue on Blizzard's servers or even a network/DNS outage. Either way, use whatever works for you. :)

**Comment by ekhoury2000** [comment]
Hi @Dids @kixelated ,

Thanks for all the answers guys,

@kixelated i will now create a server with your 3 images as per your recommendation and test.

@Dids can you please clarify the port binding thing, (--network host), does this mean when running the 3 images, i should add this option with the host IP address to improve performace?

I usually do not specify an IP address for DNS so it listens to all 0.0.0.0/53:53udp.

please send me an example so i can include this option in my tests

Thanks in advance

**Comment by ekhoury2000** [comment]
Hi @kixelated ,

I tried running your froked image of steamcache, it was working fine in caching until i used the redirection to redirect the cache dir to /tmp/steamcache , mounted as a shared storage.

The weird thing is that the folders are being created of my shared storage (5f, 34, 48, etc...) which proves that the issue is not a permission issue, but all folders are remaining empty. any ideas?

Also, if i wanted to integrate in ur image the watchlog.sh from steamcache/steamcache since it tails the log with different colors, can i just copy the script or something?

Thanks in advance,

**Comment by kixelated** [comment]
@ekhoury2000 It's difficult to help without knowing your setup. I would recommend mounting the drive to `/data` and using `-v /data:/data`. My fork stores the files in a different format so make sure you delete any existing data. You should see `/data/cache` and `/data/tmp`.

You can also try connecting a shell to the steamcache container. `docker exec -it steamcache sh`. If you can write to the `/data` directory, then something is probably wrong with nginx.

watchlog.sh isn't compatible with the way I'm doing logging (so they are accessible with `docker logs`). It's possible to port the script but it would require a bit of work.

Oh and Did suggested using the `--net=host` docker command to bypass Docker's network virtualization. I personally wouldn't recommend it unless you want to experiment with higher performance.

Setting up steamcache (and alternatives) is a lot more painful than it needs to be, so I've started on a new branch to address that. It might not work perfectly but you can try it if you want: https://github.com/kixelated/steamcache/tree/future

**Comment by Dids** [comment]
Just a heads up that I do recall running into permission issues at some point, and stopping the containers and deleting the entire host mounted directory (ie. `/data`) fixed it. I might've manually created the directory before, which messed up the permissions.

**Comment by kixelated** [comment]
@ekhoury2000 I still wouldn't recommend using the host network stack until you get everything working. "high performance" in this case means marginally faster but less likely to work. I actually just tried the host stack on my Mac and it didn't work at all.

**Comment by ekhoury2000** [comment]
@kixelated ok thanks for the advise, i was just checking the syntax (--network host ) or (--net=host), but i won't run it until all is working.

@Dids its not a persmission issue, since all folders in cache are being created and files in tmp are also being created, just all the directories inside /cache are empty.

@kixelated what would you suggest? forget this setup and use your future one? can we make this setup work?

**Comment by kixelated** [comment]
@ekhoury2000 You can definitely get this config working. It sounds like you're just having issues with docker and the network drive. My future branch probably won't help there.

**Comment by ekhoury2000** [comment]
@kixelated ok thank you. Anything you want me to test or try?

@kixelated seems an issue while renaming from /tmp to /steamcache

2017/04/03 12:01:20 [crit] 6#6: *15 rename() "/data/tmp/0000000029" to "/data/ca                                                che/46/fb/10d4a706fbc6271e019d090eae23fb46" failed (16: Resource busy) while rea                                                ding upstream, client: 192.168.1.4, server: steam, request: "GET /depot/200211/c                                                hunk/82aa70132ec3fc78072dd1b3bde9db360596cc7f?l=14&e=1491825560&sid=64130457&h=8                                                5f4951e2afb4710d236701241fa936912d99bea HTTP/1.1", upstream: "http://162.254.197                                                .25:80/depot/200211/chunk/82aa70132ec3fc78072dd1b3bde9db360596cc7f?l=14&e=149182                                                5560&sid=64130457&h=85f4951e2afb4710d236701241fa936912d99bea", host: "valve515.s                                                teamcontent.com"
