### ISSUE TITLE
Can the cache functionality be checked by a script?

### ISSUE THREAD

**Issue by JohanvdHoven** [steamcache/generic#11]
In the Steamcache guide on ARS Technica (https://arstechnica.com/gaming/2017/01/building-a-local-steam-caching-server-to-ease-the-bandwidth-blues/) there is a script on how to check if the cache functions properly.

sudo docker exec steamcache /scripts/watchlog.sh

Is a similar script available to check on the cache function in the Generic cache?

**Comment by JasonRivers** [comment]
You can check the log file, located in /data/logs/access.log with:

`docker exec steamcache tail -f /data/logs/access.log`

It's not quite as pretty as the watchlog script currently, but we're working on some extra features for these images that will use a local version of steamdb which we've extended to have an API for our uses (the person working on that has it in his own repository at the moment as it's not ready).

The Watchlog.sh script is not hugely efficient which is why it's disabled as the default output now, This is because for each line in the log file it's spawning a few processes to colour the lines, get the depot data, etc. On a large network (around 400 users) the CPU was working quite hard just to display the log in this way. There's a python script (watchlog.py) but it's currently WIP and will be updated properly when the rest of the work is done with the local steamdb API system.

**Comment by dsozzi** [comment]
Hi, I'm currently using the tail command as suggested above but it's quite difficult to understand if the cache is working or not.

I'm currently keep getting the following line repeated 

```
172.17.0.1 / 10.0.0.5, 172.17.0.1, 172.17.0.1, 172.17.0.1, 172.17.0.1, 172.17.0.1, 172.17.0.1, 172.17.0.1, 172.17.0.1, 172.17.0.1 - - [15/Jun/2018:08:14:04 +0000] "GET /favicon.ico HTTP/1.0" 504 586 "http://10.0.0.101/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36" "MISS" "10.0.0.101" "bytes=0-1048575"
````

I'm not sure who is asking this favicon.ico

Is it possible to know which other logs are available in the log folder?

thanks
