### ISSUE TITLE
Run generic lancache together with steamcache?

### ISSUE THREAD

**Issue by JohanvdHoven** [steamcache/generic#4]
Is it possible to run this generic lancache on the same machine which run steamcache?
I get a bind x.x.x.x:80 failed:port is already allocated error message.

**Comment by GotenXiao** [comment]
It's not really required - the generic cache will cache Steam content as well. The only difference is that the on-disk format is not as readily transferable between hosts with the generic cache, but the steamcache image effectively mirrors the content of the Steam CDNs.

If you wanted to do this, however, you'd need to run the containers on separate IPs (that is, not using `--net=host` - check the Docker networking documentation for more details), and you'd need to do some tweaks to the DNS setup.

**Comment by JohanvdHoven** [comment]
If I use the generic lancache, would it also cache steam content right out of the box?
I am confused about your suggestion to run the containers on seperate IPs. Can you explain why this is necessary?

**Comment by JasonRivers** [comment]
The generic image will cache steam content, but not as efficiently as the steamcache image (I've not done any work on the generic image, this is just my understanding from @GotenXiao and @mintopia).

Regarding the IPs, you can only host a single service on a single port (in this case, port 80/TCP), So you couldn't bind both images to this port without using different IPs or going through a reverse proxy (nginx or haproxy). I do this using Rancher with it's built-in load balancer (running haproxy) as a reverse proxy on port 80/TCP, However, it takes some configuration to set all the DNS records up, You can use wildcards but there's a lot of them, which is why we have set up the DNS container.
