### ISSUE TITLE
Merge the sniproxy docker with this docker

### ISSUE THREAD

**Issue by adamradocz** [steamcache/generic#41]
Hi,

IMO this docker would be much more user friendly if it were support the HTTPS by default and wasn't required another docker container for that.

**Comment by adamradocz** [comment]
I can make a PR if you want.

**Comment by mintopia** [comment]
Hi,

Thanks for the suggestion. It has been considered before, but since an SNI proxy is only required for some services, and only one SNI proxy is required for all caching services, it's less efficient to include it within generic.

It's also preferable with docker containers to only have one process per container, whereas this would then have two.

For these reasons, I'm going to close this, but thanks for raising it.

Thanks,
Jessica
