### ISSUE TITLE
Slow initial download

### ISSUE THREAD

**Issue by gelsas** [steamcache/generic#45]
Hello,

before using steamcache I had download speeds from 45-50MB/s .

Now with steamcache (run in docker) the initial download speed is at max 8-9 MB/s per second. 

What could the issue be here?

**Comment by BelleNottelling** [comment]
I'm no expect, but I'd imagine you have an issue with your cashing server being too slow. What are it's specs?

**Comment by gelsas** [comment]
Yes exactly.

I am running it on my QNAP NAS in the Container Station (https://www.qnap.com/solution/container_station/en/)

8 TB storage
16 GB RAM
Intel(R) Celeron(R) CPU N3160 @ 1.60GHz (CPU is not the problem as far as i can see)

What else do you need to know?

**Comment by mintopia** [comment]
This container image has been tested pushing content at 10gbps, so I'm confident it's not an issue with the container itself and is more likely an issue with your deployment of it.

Can you try running it with docker networking in host mode, instead of bridged networking, that may improve performance if the bottleneck is networking.

Ultimately speed will be limited by the spec of your cache server, check CPU load and disk IO on your NAS, if either of this are too high then it will cause your cache to be slow.

**Comment by gelsas** [comment]
Hello @mintopia ,

I think I can not run it in host mode because the port 80 is already in use from the NAS. Any suggestions how to make it work in host mode then ?

I just tried to download a file via wget directly from within the docker container itself
(wget -O /dev/null http://cachefly.cachefly.net/100mb.test) 
The file took about 2 seconds to download.

When downloading a 5GB steam game and using the docker stats command I get this:
CONTAINER 2a2a69e6146e
CPU %    13.57%
MEM USAGE / LIMIT  54.1MiB / 15.56GiB
MEM %   0.34%
NET I/O     724MB / 507MB 
BLOCK I/O 118MB / 639kB  

What does it exactly mean and what can I do to make it work better ? 
(Also is it normal that the MEM usage is so low ?)

**Comment by JasonRivers** [comment]
The container doesn't use a lot of actual memory, around 50MiB sounds correct, What is not shown in there is how much of the memory is used for cache data (handled by the kernel) - this is the part of the container that uses memory, and this is a non-issue. The problem with the docker stats is it's a one-shot, would you be able to log this to file periodically while downloading a game? something like:
```sh
while true; do
date | tee -a /tmp/steam-download
docker stats --no-stream | tee -a /tmp/steam-download
sleep 10
done
```
Once downloaded you can hit ^C to cancel that and then attach the file to this issue, this way we can look at what's happening over time.

Is there anything else running on the NAS (other than the NAS system itself) I do have access to a QNAP NAS running intel, but my testing on this might be limited as it's at the office.

**Comment by gelsas** [comment]
Hello I just did as you suggested:
[steam-download.txt](https://github.com/steamcache/generic/files/2318935/steam-download.txt)

This is the correct docker id: 2a2a69e6146e 
The other one is: https://github.com/janeczku/calibre-web (it just displays my ebook collection in my local network)

Plex Media Server is running on there but it does not write/read anything when it is not used.

I hope the log is helping. If not it would be great if you may test it on the QNAP aswell. Maybe it is some other QNAP related issue.

**Comment by TheGrandPackard** [comment]
I also noticed this being the case the first time I download games with an empty cache. I get ~72Mbps of the ~100Mbps I would normally get through my WAN connection if I didn't use the caching server. This is inconvenient but I can get upwards of 700Mbps (running from a single SSD) for subsequent downloads once it has been cached, so I just pre-cache the games I know we'll be playing ahead of time.

If there was a way to maximize the initial download, it'd be great, but I'll keep using it as is.

**Comment by mintopia** [comment]
I think it may be a QNAP related issue, I'd expect to see the container memory usage much higher - the container should be using as much RAM as it can get - since it should be caching files that are accessed in RAM. I'd be interested if anyone else with a QNAP is also getting this performance issue.

@TheGrandPackard That is normal. It's a caching server - _it can't speed up the initial download_. However, once it's on your cache server, it will give quick downloads to any other clients.

Priming the cache with content is a good thing to do before a LAN party.

**Comment by gelsas** [comment]
@JasonRivers Could you test it aswell ?
