### ISSUE TITLE
Analyzing the log files for statistics

### ISSUE THREAD

**Issue by Spiderschwein** [steamcache/generic#69]
### Describe the issue you are having
Its not an issue direct, its more a question on how you handle the log file watching.
I like to analyze the log files in production use to see how much files are served from the cache and how much not. 
Are there any tool you have for this purpose? 

### How are you running the container(s)?
The docker-compose file from the docker-compose Repository.
One container of the generic cache for every service.
Logfiles under `/data/{service}/logs/access.log`

### DNS Configuration
No problem, everything works fine

**Comment by mgjuhler** [comment]
Hi,
I also use steamcache generic for my cache server. I have spent a lot of time getting it to work and now I finally have a solution that can be used. Now i can see numbers and graphs on a web interface :)

You need the following things:

**Install lancache-filebeat**
Description: run on your cache server which sends logs to the ELK server. You need to change the file `/etc/filebeat/filebeat.yml` so its working with the logs from your games cache.
```
name: "lancache"
filebeat.prospectors:
- type: log
  paths:
    - /data/steam/logs/*.log
    - /data/wsus/logs/*.log
    - /data/blizzard/logs/*.log
    - /data/origin/logs/*.log

output.logstash:
  hosts: ["12.34.56.78:5044"]
```
12.34.56.78 is the ELK server.
Link: https://github.com/zeropingheroes/lancache-filebeat

**Change steamcache log format**
Start bash on the game cache docker `docker exec -it ID bash` (install nano or vi)
Edit the file `/etc/nginx/conf.d/10_log_format.conf` and replace the xx with:

```
log_format cachelog
                        '[$time_local] '
                        '$remote_addr '
                        '$request_method '
                        '"$request_uri" '
                        '$http_range '
                        '$slice_range '
                        '$status '
                        '$body_bytes_sent '
                        '$upstream_response_length '
                        '$upstream_cache_status '
                        '$host '
                        '$upstream_status '
                        '$upstream_response_time '
                        '"$http_user_agent"';
```

**Install lancache-elk**
Just follow the guide.
Link: https://github.com/zeropingheroes/lancache-elk

Notice that stats for blizzard and origin is a bit strange due to slice in nginx.


I hope you can use it :)

**Comment by danielriddell21** [comment]
Thank you for the above, it works!

**Comment by mgjuhler** [comment]
How did you fix the problem you had?

**Comment by danielriddell21** [comment]
> How did you fix the problem you had?

Restarted filebeat :)

**Comment by bobland1** [comment]
Is there a way to see the current used bandwidth?

**Comment by bobland1** [comment]
Also a way to see the steam games stored not the steam IDs

**Comment by VibroAxe** [comment]
@mgjuhler for reference editing the log format directly in a running docker is not a good way to do this as the changes may be reset at any time/restart (thats the whole point of docker). You would be best to make your own overlay from generic and update the logformat file in that instead. (steamcache/monolithic does this amonsgt others so you might be able to look at that dockerfile/construct for ideas) 

I would also suggest that this would want to be in the setup instructions for zph/lancache-elk not in here so I'm going to close this issue
