### ISSUE TITLE
how to update?

### ISSUE THREAD

**Issue by drobskind** [steamcache/generic#88]
### Describe the issue you are having
I am wondering and don't seem to find it anywhere.
How do I update an active running lancache server?
I just read, that now EPIC is also available for caching.
So will it just work out of the box, on my cache server I set up 2 month ago?
Or is there any update command I need to run?
Or do I even have to install everything again?

Thanks!

### How are you running the container(s)?
```
<!-- Paste your docker run commands or your docker-compose file here -->
```

### DNS Configuration
```
<!-- Paste your docker run command for the DNS container OR explain how you have setup DNS on your network to point to the container -->
```
### Output of container(s)
```
<!-- Paste any output from the containers here - This will help us identify any issues faster -->
```

**Comment by unspec** [comment]
Hi,

Not sure if you are still having the issue, but for anyone reading this, if you restart lancache-dns it will repull the cache domains list and add/remove any hostnames (such as epic etc) that have changed since you last started the container.

Feel free to reopen if you are still having issues.
