### ISSUE TITLE
Question: Is there a way to see wich / howmany  games or updates are cached

### ISSUE THREAD

**Issue by Rubenne** [steamcache/generic#92]
basically title says all, I wanna see what I have cached in my server. Ideally would be to have / create a dashboard

**Comment by unspec** [comment]
The short answer is no. nginx has no real concept of a game - just chunks/slices of data - and so it can't really tell you what games are presently in your cache.

Many people choose to send their generic logs to something like ELK to generate reports on what has been downloaded etc - but even that is historic stats rather than a current "i have games x/y/z in the cache right now".

If you are interested in analysing your logs then https://github.com/lancachenet/logstash might be a useful starting point.
